import { chromium } from 'playwright';
const BASE = process.env.SPRAK_URL || 'http://localhost:4173';
const b = await chromium.launch({...(process.env.CHROME_PATH ? {executablePath: process.env.CHROME_PATH} : {})});
const p = await b.newPage({ viewport:{width:390,height:844}, deviceScaleFactor:2 });
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push('PAGEERR '+e.message));
await p.addInitScript(()=>{ const m={speak:()=>{},cancel:()=>{},getVoices:()=>[{name:'Google Deutsch',lang:'de-DE'}],set onvoiceschanged(f){},get onvoiceschanged(){return null}};
  Object.defineProperty(window,'speechSynthesis',{value:m,configurable:true,writable:true}); });
await p.goto(BASE); await p.waitForTimeout(250);
await p.click('.pathRow:not(.locked)'); await p.waitForTimeout(300);
await p.click('button.btn'); await p.waitForTimeout(200); await p.click('.pathRow'); await p.waitForTimeout(400);
await p.click('.pathRow'); await p.waitForTimeout(500);
const t = await p.textContent('.screen');
console.log('welcome practice card gone:', !t.includes('A welcome from the heart'));
console.log('no Hear it / Say it on step 1:', await p.locator('.speakbar').count()===0);
console.log('Klara still greets in German:', t.includes('Herzlich willkommen'));
console.log('board present:', t.includes('Meine Vorstellung'), '| blanks:', await p.locator('input[type=text]').count());
await p.screenshot({path:'tests/shots/l1-clean.png', fullPage:true});
for(const [id,v] of [['b_name','Shreya'],['b_age','27'],['b_country','Indien'],['b_city','Berlin'],['b_lang','Englisch']]) await p.fill('#'+id,v);
await p.click('#g_f'); await p.waitForTimeout(250);
console.log('age blank present:', await p.locator('#b_age').count()===1);
console.log('gender chips:', await p.locator('.gchip').count());
await p.click('#l1go'); await p.waitForTimeout(450);
const n = await p.locator('.linerow').count();
console.log('step 3 reached, lines:', n);
const lt = await p.textContent('.screen');
console.log('age line said:', lt.includes('27 Jahre alt'));
console.log('gender line said:', lt.includes('eine Frau'));
console.log('ERRORS:', errs.length? errs.slice(0,4):'none 🎉');
await b.close();
